// Central place for all projects on ficho-films

const PROJECTS = [
 // === HERO / BIG FEATURED PROJECTS ===
{
  id: "season-of-the-witch",
  title: "Season of the Witch",
  year: 2011,
  role: "coordination",
  roleLabel: "Production Coordinator (Cro Crew)",
  type: "Feature Film",
  client: "Atlas Entertainment, Relativity Media & BlueSky Films Croatia",
  stars: "Nicolas Cage, Ron Perlman",
  link: "https://www.imdb.com/title/tt0479997/",
  image: "images/season-of-the-witch.png",
  featuredSize: "big",
   teaserVideo: "videos/season-of-the-witch-teaser.mp4",
},
{
  id: "the-hunting-party",
  title: "The Hunting Party",
  year: 2007,
  role: "location",
  roleLabel: "Location Scout",
  type: "Feature Film",
  client: "Jadran Film",
  stars: "Richard Gere, Terrence Howard, Jesse Eisenberg, Diane Kruger",
  link: "https://www.imdb.com/title/tt0455782/",
  image: "images/the-hunting-party.png",
  featuredSize: "big",
     teaserVideo: "videos/hunting-party-teaser.mp4",
},

// === SMALL FEATURED PROJECTS ===
{
  id: "un-altro-mondo",
  title: "Un altro mondo",
  // year: 2010,
  role: "coordination",
  roleLabel: "Kenya Production Staff",
  type: "Feature Film",
  client: "Cattleya, Universal Pictures International (UPI) & Blue Sky Films Kenya",
  link: "https://www.imdb.com/title/tt1544601/",
  image: "images/un-altro-mondo.png",
  featuredSize: "small",
     teaserVideo: "videos/mondo.mp4",
},
{
  id: "eyjafjallajokull",
  title: "Eyjafjallajökull",
  // year: 2013,
  role: "director",
  roleLabel: "Third Assistant Director",
  type: "Feature Film",
  client: "Quad, TF1 Films Production & BlueSky Films Croatia",
  link: "https://www.imdb.com/title/tt2207072/",
  image: "images/eyjafjallajokull.png",
  featuredSize: "small",
  teaserVideo: "videos/vulcan.mp4",
},
{
  id: "max-schmeling",
  title: "Max Schmeling",
  year: 2010,
  role: "location",
  roleLabel: "Assistant Location Manager",
  type: "Feature Film",
  client: "Boll Kino Beteiligungs GmbH & Co. KG, Herold Productions & Jadran Film",
  stars: "Henry Maske, Heino Ferch, Susanne Wuest",
  link: "https://www.imdb.com/title/tt1361828/",
  image: "images/max-schmeling.png",
  featuredSize: "small",
  teaserVideo: "videos/schmelling.mp4",
},

  // === AD ===
  {
  id: "liebe",
  title: "Liebe ist nur ein Wort",
  // year: 2010,
  role: "director",
  roleLabel: "Unit AD",
  type: "Feature Film",
  client: "MOOVIE the art of entertainment GmbH, Zweites Deutsches Fernsehen (ZDF)",
  link: "https://www.imdb.com/title/tt1471333/companycredits/",
  image: "images/liebe.png",
  featuredSize: false,
},
{
  id: "halima",
  title: "Halima's Path",
  // year: 2012,
  role: "director",
  roleLabel: "2nd Assistant Director",
  type: "Feature Film",
  client: "Arkadena / FIST Production / HRT",
  link: "https://www.imdb.com/title/tt2244877/",
  image: "images/halima.png",
  featuredSize: false,
},

   {
    id: "martini-moments",
    title: "Martini Moments - TVC",
    year: null,
    role: "director",
    roleLabel: "2nd Assistant Director",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/martini-moments/",
    image: "/images/project_pics/martini.jpg",
    featured: false,
  },

  // === LOCATIONS ===
  {
    id: "sanjam",
    title: "Sanjam - Music Video",
    year: null,
    role: "location",
    roleLabel: "Location Manager",
    type: "Production Company Collaboration",
    client: "Elemental",
    link: "https://www.youtube.com/watch?v=2EjcnDR5TC8",
    image: "images/project_pics/sanjam.jpg",
    featured: false,
  },
    {
    id: "scouting-croatia",
    title: "Scouting Croatia",
    year: null,
    role: "location",
    roleLabel: "Location Manager",
    type: "Production Company Collaboration",
    client: "Film Scouting Croatia association",
    link: "http://scoutingcroatia.com/",
    image: "images/project_pics/scouting_croatia.jpg",
    featured: false,
  },

      {
    id: "vindija",
    title: "Vindija - TVC",
    year: null,
    role: "location",
    roleLabel: "Location Manager",
    type: "Production Company Collaboration",
    client: "Luminus Studio",
    link: "https://www.screenglobalproduction.com/country/croatia/profile/luminus-studio",
    image: "images/project_pics/vindija.jpg",
    featured: false,
  },

       {
    id: "nlc",
    title: "Odjednom Ti - Series Pilot",
    year: null,
    role: "location",
    roleLabel: "Location Manager",
    type: "Production Company Collaboration",
    client: "NLC Media & Plan 9",
    link: "https://www.plan9.hr/",
    image: "images/project_pics/nlc.jpg",
    featured: false,
  },

         {
    id: "sky-scout",
    title: "Blue Sky Films Croatia ",
    year: null,
    role: "location",
    roleLabel: "Location Scout",
    type: "Production Company Collaboration",
    client: "Permanent employment (2003 - 2013)",
    link: "https://www.blueskyadriatic.com/",
    image: "images/project_pics/bluesky.png",
    featured: false,
  },
           {
    id: "ratkajevi",
    title: "Ponos Ratkajevih - TV series",
    year: null,
    role: "location",
    roleLabel: "Location Manager",
    type: "Production Company Collaboration",
    client: "AVA Production Group",
    link: "https://www.youtube.com/@avaprodukcija",
    image: "images/project_pics/ratkajevi.png",
    featured: false,
  },

  {
    id: "lotto-649-farm",
    title: "Lotto 649 – Farm",
    year: null,
    role: "location",
    roleLabel: "Locations Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/lotto-649-farm/",
    image: "images/project_pics/lotto.png",
    featured: false,
  },

  // === PRODUCTION COORDINATION / STAFF ===
  {
    id: "un-altro-mondo",
    title: "Un altro mondo",
    // year: 2010,
    role: "coordination",
    roleLabel: "Kenya Production Staff",
    type: "Feature Film",
    client: "Un altro mondo",
    link: "https://www.imdb.com/title/tt1544601/",
    image: "https://m.media-amazon.com/images/M/MV5BMTA0OTQ2NTMyNDVeQTJeQWpwZ15BbWU3MDk0NDcxNzQ@._V1_.jpg",
    featured: false,
  },

  // === TRANSPORTATION MANAGER ===
  {
    id: "spectre-heineken",
    title: "Spectre James Bond 007 | The Chase (Heineken Spot)",
    year: null,
    role: "coordination",
    roleLabel: "Transportation Manager",
    type: "Commercial",
    client: "Mainframe Productions",
    link: "https://www.youtube.com/watch?v=-0-AJYlJcF0",
    image: "images/project_pics/bond.jpg",
    featured: false,
  },

  // === PRODUCTION COORDINATOR – COMMERCIALS ===

 

    {
    id: "sole-ore",
    title: "Sole 24 Ore",
    year: null,
    role: "coordination",
    roleLabel: "Production Coordinator",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "videos/sole-ore.mov",
    image: "images/project_pics/sole-ore.jpg",
    featured: false,
  },

   {
    id: "kellogs",
    title: "Kellog's All-Bran",
    year: null,
    role: "coordination",
    roleLabel: "Production Coordinator",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com",
    image: "/images/project_pics/kellogs.jpg",
    featured: false,
  },

   {
    id: "samsung",
    title: "Samsung Galaxy (2007 TVC)",
    year: null,
    role: "coordination",
    roleLabel: "Production Coordinator",
    type: "Commercial",
    client: "Blue Sky Films Croatia",
    link: "https://www.blueskyadriatic.com",
    image: "images/project_pics/samsung.jpg",
    featured: false,
  },

  // === PRODUCTION MANAGER ===
  {
    id: "mazda-2",
    title: "New Mazda 2",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/new-mazda-2/",
    image: "/images/project_pics/mazda02.jpg",
    featured: false,
  },
  {
    id: "bakers-meaty-meals",
    title: "Bakers Meaty Meals – The Italian Dog",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films & Ridley Scott Association",
    link: "https://www.blueskyadriatic.com/film/bakers-meaty-meals-the-italian-dog/",
    image: "images/project_pics/bakers.jpg",
    featured: false,
  },
  {
    id: "buitoni-silenzio",
    title: "Buitoni – Il silenzio di Buitoni",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/buitoni-il-silenzio-di-buitoni/",
    image: "images/project_pics/buitoni.jpg",
    featured: false,
  },
   {
    id: "fernet-branca",
    title: "Fernet Branca TVC",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/fernet-branca/",
    image: "images/project_pics/fernet.jpg",
    featured: false,
  },

  // === PRODUCER ===
  {
    id: "taubeki",
    title: "Taubeki - short film",
    // year: 2014,
    role: "producer",
    roleLabel: "Producer",
    type: "Short Film",
    client: "C47 film d.o.o.",
    link: "https://www.imdb.com/title/tt3627382/",
    image: "images/project_pics/taubeki.jpg",
    featured: false,
  },
  {
    id: "c47-films",
    title: "C47 Films",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Production Company Collaboration",
    client: "Film Production Company",
    link: "https://www.c47film.hr",
    image: "images/project_pics/c47_logo.png",
    featured: false,
  },

    {
    id: "rabbit",
    title: "Don't Follow the White Rabbit (Music video)",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Production Company Collaboration",
    client: "Reserved Life",
    link: "https://vimeo.com/79227335",
    image: "/images/project_pics/rabbit.png",
    featured: false,
  },
   {
    id: "scroll",
    title: "Soap - MTV Music Video",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Production Company Collaboration",
    client: "Scroll Band",
    link: "https://www.youtube.com/watch?v=7OXN6z8Wlbs",
    image: "/images/project_pics/scroll.png",
    featured: false,
  },
   {
    id: "muscle",
    title: "New School Blood Trial - Official Music Video",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Music Video",
    client: "Muscle Tribe of Danger and Excellence",
    link: "https://www.youtube.com/watch?v=Ph5pBiWWoq0",
    image: "/images/project_pics/muscle.jpeg",
    featured: false,
  },

  {
    id: "casting-croatia",
    title: "Casting Croatia",
    year: null,
    role: "director",
    roleLabel: "Casting Manager",
    type: "Casting",
    client: "Permanently employed (2011 - 2015)",
    link: "https://www.castingcroatia.com",
    image: "/images/project_pics/cc-logo.jpg",
    featured: false,
  },

  // === EVENT MANAGER PLACEHOLDER ===
    {
   id: "event-polyfest-2025",
    title: "PolyFest",
    year: null,
    role: "event",
    roleLabel: "Main Event Manager",
    type: "Events",
    client: "Poly Speed Dating",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "images/project_pics/polyfest.png",
    featured: false,
  },
   {
    id: "event-flashback-90s",
    title: "Flashback 90's Party",
    year: null,
    role: "event",
    roleLabel: "Weekly party series",
    type: "Events",
    client: "Discotheque Saloon | Zagreb",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "images/project_pics/saloon.jpg",
    featured: false,
  },
   {
 id: "event-burnhalla-2026",
    title: "BurnHalla",
    year: null,
    role: "event",
    roleLabel: "Site Lead 2026",
    type: "Events",
    client: "Berlin Burner e. V.",
    link: "https://burnhalla.com/",
    image: "images/project_pics/burnhalla.png",
    featured: false,
      },
     {
 id: "psd",
    title: "Poly Speed Dating",
    year: null,
    role: "event",
    roleLabel: "Project Lead",
    type: "Events",
    client: "PSD Berlin",
    link: "https://poly-speed-dating.onrender.com",
    image: "/images/project_pics/psd.png",
    featured: false,
    
  },
      {
 id: "bcom-welcome",
    title: "B.Welcome (Booking Cares Project)",
    year: null,
    role: "event",
    roleLabel: "Project Lead",
    type: "Events",
    client: "Booking.com GmbH",
    link: "https://www.bookingcares.com/",
    image: "images/project_pics/b-cares.jpeg",
    featured: false,
      },

                       {
 id: "workshop",
    title: "KiezBurn CrepesClub",
    year: null,
    role: "event",
    roleLabel: "Camp Lead & Workshop Facilitator (2025)",
    type: "Events",
    client: "Berlin Burner e. V.",
    link: "https://mmm.kiezburn.org/",
    image: "/images/project_pics/kiezburn.jpeg",
    featured: false,
      },

        {
       id: "jelaousy",
    title: "Jealousy; a path to Growth",
    year: null,
    role: "event",
    roleLabel: "Workshop Facilitator",
    type: "Events",
    client: "PolyFest2025.",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "images/project_pics/jealousy.png",
    featured: false,
      },

                  {
 id: "zagimun",
    title: "ZagIMUN Conference",
    year: null,
    role: "event",
    roleLabel: "Logistics Manager  (2007-2010)",
    type: "Events",
    client: "ZagIMUN Organization",
    link: "zagimun.org",
    image: "images/project_pics/zagimun.jpg",
    featured: false,
      },

                        {
 id: "emotional-intelligence",
    title: "Stronger Bonds",
    year: null,
    role: "event",
    roleLabel: "Workshop Fascilitator",
    type: "Events",
    client: "Workshop: Fostering Social Connection & Emotional Intelligence",
    link: "#",
    image: "images/project_pics/stronger-bonds.png",
    featured: false,
      },

         {
 id: "meuz",
    title: "MEUZ Conference",
    year: null,
    role: "event",
    roleLabel: "Logistics Manager & Chairperson",
    type: "Events",
    client: "Hermes NGO",
    link: "https://hermes.hr/meuz/",
    image: "images/project_pics/meuz.png",
    featured: false,
      },
      
         {
 id: "sofimun",
    title: "SofiMUN Conference",
    year: null,
    role: "event",
    roleLabel: "Security Council Chairperson",
    type: "Events",
    client: "SOFIMUN Foundation",
    link: "https://unglobalcompact.org/what-is-gc/participants/12202-SOFIMUN-Foundation",
    image: "images/project_pics/sofimun.jpg",
    featured: false,
      },

         {
 id: "scappy",
    title: "ScappyLand - Candy Party",
    year: null,
    role: "event",
    roleLabel: "Promotion Visual Manager",
    type: "Events",
    client: "Scappy",
    link: "https://www.index.hr/lajk/poster/71905/candy-party-powered-by-scappy-land-14032009-15",
    image: "images/project_pics/scappy.jpg",
    featured: false,
      },

];
