// Central place for all projects on ficho-films

const PROJECTS = [
 // === HERO / BIG FEATURED PROJECTS ===
{
  id: "season-of-the-witch",
  title: "Season of the Witch",
  year: 2011,
  role: "coordination",
  roleLabel: "Production Coordinator",
  type: "Feature Film",
  client: "Atlas Entertainment, Relativity Media & BlueSky Films Croatia",
  stars: "Nicolas Cage, Ron Perlman",
  link: "https://www.imdb.com/title/tt0479997/",
  image: "images/season-of-the-witch.png",
  featuredSize: "big",
   teaserVideo: "videos/season-of-the-witch-teaser.mp4",
},
{
  id: "the-hunting-party",
  title: "The Hunting Party",
  year: 2007,
  role: "location",
  roleLabel: "Location Scout",
  type: "Feature Film",
  client: "Jadran Film",
  stars: "Richard Gere, Terrence Howard, Jesse Eisenberg, Diane Kruger",
  link: "https://www.imdb.com/title/tt0455782/",
  image: "images/the-hunting-party.png",
  featuredSize: "big",
     teaserVideo: "videos/hunting-party-teaser.mp4",
},

// === SMALL FEATURED PROJECTS ===
{
  id: "un-altro-mondo",
  title: "Un altro mondo",
  year: 2010,
  role: "coordination",
  roleLabel: "Kenya Production Staff",
  type: "Feature Film",
  client: "Un altro mondo",
  link: "https://www.imdb.com/title/tt1544601/",
  image: "images/un-altro-mondo.png",
  featuredSize: "small",
},
{
  id: "eyjafjallajokull",
  title: "Eyjafjallajökull",
  year: 2013,
  role: "director",
  roleLabel: "Third Assistant Director",
  type: "Feature Film",
  client: "",
  link: "#",
  image: "images/eyjafjallajokull.png",
  featuredSize: "small",
},
{
  id: "max-schmeling",
  title: 'Henry Maske in "Max Schmeling"',
  year: 2010,
  role: "location",
  roleLabel: "Assistant Location Manager",
  type: "Feature Film",
  client: "Max Schmeling",
  link: "#",
  image: "images/max-schmeling.png",
  featuredSize: "small",
},

  // === LOCATION MANAGEMENT ===
  {
    id: "max-schmeling",
    title: 'Henry Maske in "Max Schmeling"',
    year: 2010,
    role: "location",
    roleLabel: "Assistant Location Manager",
    type: "Feature Film",
    client: "Max Schmeling",
    link: "#",
    image: "http://static.photos/https://m.media-amazon.com/images/M/MV5BMTgyNzA1MTcwNF5BMl5BanBnXkFtZTcwMzA2OTMwNA@@._V1_.jpg/640x360/5",
    featured: false,
  },

  // === AD ===
  {
  id: "liebe",
  title: "Liebe ist nur ein Wort",
  year: 2010,
  role: "director",
  roleLabel: "Assistant Director & Units AD",
  type: "Feature Film",
  client: "MOOVIE the art of entertainment GmbH, Zweites Deutsches Fernsehen (ZDF)",
  link: "https://www.imdb.com/title/tt1471333/companycredits/",
  image: "images/eyjafjallajokull.png",
  featuredSize: "small",
},

  // === PRODUCTION COORDINATION / STAFF ===
  {
    id: "un-altro-mondo",
    title: "Un altro mondo",
    year: 2010,
    role: "coordination",
    roleLabel: "Kenya Production Staff",
    type: "Feature Film",
    client: "Un altro mondo",
    link: "https://www.imdb.com/title/tt1544601/",
    image: "https://m.media-amazon.com/images/M/MV5BMTA0OTQ2NTMyNDVeQTJeQWpwZ15BbWU3MDk0NDcxNzQ@._V1_.jpg",
    featured: false,
  },

  // === TRANSPORTATION MANAGER ===
  {
    id: "spectre-heineken",
    title: "Spectre James Bond 007 | The Chase (Heineken Spot)",
    year: null,
    role: "transport",
    roleLabel: "Transportation Manager",
    type: "Commercial",
    client: "Mainframe Productions",
    link: "https://www.youtube.com/watch?v=-0-AJYlJcF0",
    image: "http://static.photos/cityscape/640x360/7",
    featured: false,
  },

  // === PRODUCTION COORDINATOR – COMMERCIALS ===
  {
    id: "lotto-649-farm",
    title: "Lotto 649 – Farm",
    year: null,
    role: "coordination",
    roleLabel: "Production Coordinator",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/lotto-649-farm/",
    image: "http://static.photos/outdoor/640x360/8",
    featured: false,
  },
  {
    id: "martini-moments",
    title: "Martini Moments",
    year: null,
    role: "coordination",
    roleLabel: "Production Coordinator",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/martini-moments/",
    image: "http://static.photos/food/640x360/1",
    featured: false,
  },

  // === PRODUCTION MANAGER ===
  {
    id: "mazda-2",
    title: "New Mazda 2",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/new-mazda-2/",
    image: "http://static.photos/transport/640x360/1",
    featured: false,
  },
  {
    id: "bakers-meaty-meals",
    title: "Bakers Meaty Meals – The Italian Dog",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films & Ridley Scott Association",
    link: "https://www.blueskyadriatic.com/film/bakers-meaty-meals-the-italian-dog/",
    image: "http://static.photos/animals/640x360/1",
    featured: false,
  },
  {
    id: "buitoni-silenzio",
    title: "Buitoni – Il silenzio di Buitoni",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/buitoni-il-silenzio-di-buitoni/",
    image: "http://static.photos/food/640x360/2",
    featured: false,
  },
    {
    id: "fig",
    title: "The Proper Way to Eat a Fig in Society",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Video",
    client: "Igor",
    link: "https://www.imdb.com/title/tt3630160/",
    image: "http://static.photos/transport/640x360/1",
    featured: false,
  },
  {
    id: "fernet-branca",
    title: "Fernet Branca",
    year: null,
    role: "manager",
    roleLabel: "Production Manager",
    type: "Commercial",
    client: "Blue Sky Films",
    link: "https://www.blueskyadriatic.com/film/fernet-branca/",
    image: "http://static.photos/drinks/640x360/1",
    featured: false,
  },

  // === PRODUCER ===
  {
    id: "taubeki",
    title: "Taubeki",
    year: 2014,
    role: "producer",
    roleLabel: "Producer",
    type: "Short Film",
    client: "C47 film d.o.o.",
    link: "https://www.imdb.com/title/tt3627382/",
    image: "http://static.photos/people/640x360/1",
    featured: false,
  },
  {
    id: "c47-films",
    title: "C47 Films",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Production Company Collaboration",
    client: "C47 Films",
    link: "https://www.c47film.hr",
    image: "http://static.photos/office/640x360/1",
    featured: false,
  },
   {
    id: "c47-films",
    title: "Scroll Band - 'Soap' Music Video",
    year: null,
    role: "producer",
    roleLabel: "Producer",
    type: "Production Company Collaboration",
    client: "Scroll Band",
    link: "https://www.youtube.com/watch?v=7OXN6z8Wlbs",
    image: "http://static.photos/office/640x360/1",
    featured: false,
  },

  // === CASTINGS MANAGER ===
  {
    id: "casting-croatia",
    title: "Casting Croatia",
    year: null,
    role: "casting",
    roleLabel: "Castings Manager",
    type: "Casting",
    client: "Casting Croatia",
    link: "https://www.castingcroatia.com",
    image: "http://static.photos/people/640x360/2",
    featured: false,
  },

  // === EVENT MANAGER PLACEHOLDER ===
    {
    id: "event-placeholder",
    title: "Festivals & Events",
    year: null,
    role: "event",
    roleLabel: "PolyFest 2025",
    type: "Events",
    client: "",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "http://static.photos/music/640x360/1",
    featured: false,
  },
   {
    id: "event-placeholder",
    title: "Weekly party series",
    year: null,
    role: "event",
    roleLabel: "Flashback 90's Trash Party",
    type: "Events",
    client: "Discotheque Saloon | Zagreb",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "http://static.photos/music/640x360/1",
    featured: false,
  },
   {
    id: "event-placeholder",
    title: "Festivals & Events",
    year: null,
    role: "Site Lead",
    roleLabel: "BurnHalla 2026",
    type: "Events",
    client: "Berlin Burner e. V.",
    link: "https://poly-speed-dating.onrender.com/polyfest.html",
    image: "http://static.photos/music/640x360/1",
    featured: false,
  }
];
